name: 51 Scan Docker Image
on:
  workflow_dispatch:
    inputs:
      image-tag:
        type: string
        description: 'The name of the docker image to scan'
        required: true

  workflow_call:
    inputs:
      image-tag:
        type: string
        description: 'The name of the docker image to scan'
        required: true
env:
  REGISTRY: ghcr.io
  # This line converts the repository name to lowercase automatically
  IMAGE_NAME: ${{ github.repository }}
  FULL_IMAGE_NAME: ghcr.io/${{ github.repository }}:${{ inputs.image-tag || github.event.inputs.image-tag }}

jobs:
  container-image-scan:
    name: Container Image Scan
    runs-on: ubuntu-latest
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker Image
        # Use the lowercase conversion here
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker pull ghcr.io/${REPO_LOWER}:${{ inputs.image-tag || github.event.inputs.image-tag }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.33.1
        with:
          # Use the lowercase conversion for image-ref as well
          image-ref: ghcr.io/${{ github.repository_owner }}/githubdevsecops:${{ inputs.image-tag || github.event.inputs.image-tag }}
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
