name: 00 - Main CI / CD Pipeline

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write
  issues: read
  actions: read
  security-events: write

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit

  sast:
    name: SAST
    needs: build  # Runs after Build
    uses: ./.github/workflows/sast.yml
    secrets: inherit

  semgrep:
    name: SEMGREP
    needs: sast   # Runs after SAST
    uses: ./.github/workflows/semgrep.yml
    secrets: inherit

  docker:
    name: Build docker image
    needs: semgrep # Runs after Semgrep
    uses: ./.github/workflows/docker.yml
    secrets: inherit

  container-image-scan:
    name: Scan docker image
    needs: docker  # Runs after Docker
    uses: ./.github/workflows/container-image-scan.yml
    secrets: inherit
    with:
      image-tag: ${{ needs.docker.outputs.image-tag }}