
name: 00 - Main CI / CD Pipeline

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit

  # sca:
  #   needs: build
  #   name: SCA
  #   uses: ./.github/workflows/sca.yml
  #   secrets: inherit

  sast:
    needs: build
    name: SAST
    uses: ./.github/workflows/sast.yml
    secrets: inherit
